# Generated by Django 5.1.7 on 2025-03-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
