# Generated by Django 5.1.7 on 2025-03-13 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('contract_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('contract', 'Contractor'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('fixedTerm', 'Fixed-term'), ('seasonal', 'Seasonal'), ('volunteer', 'Volunteer'), ('casual', 'Casual')], max_length=20, null=True)),
                ('work_schedule', models.JSONField(blank=True, default=list)),
                ('seniority', models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Tech Lead'), ('manager', 'Tech Manager'), ('executive', 'Executive'), ('associate', 'Associate'), ('principal', 'Principal'), ('vp', 'Vice President'), ('director', 'Director'), ('cLevel', 'C-Level')], max_length=20, null=True)),
                ('subscription_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('job_location', models.CharField(blank=True, max_length=150, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=150, null=True)),
                ('click_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.IntegerField(default=0, null=True)),
                ('url_direct', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
